{% set name = "earthengine-api" %}
{% set version = "1.7.40" %}
{% set sha256 = "71ba5a0380f31bd4e3d078f5660a26cabd27cca5a985c2fb8f9cd1ef42c41cef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  entry_points:
    - earthengine = ee.cli.eecli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - google-api-python-client >=2.113.0
    - google-auth >=2.55.2
    - google-auth-httplib2 >=0.4.0
    - google-cloud-storage
    - httplib2 >=0.31.2,<1dev
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - ee
    - ee.cli
  commands:
    - earthengine --help

about:
  home: https://earthengine.google.com/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Earth Engine Python API
  description: |
    The Earth Engine Python API allows developers to interact with
    Google Earth Engine, a web platform for global scale geospatial analysis.
  doc_url: https://developers.google.com/earth-engine/
  dev_url: https://github.com/google/earthengine-api/

extra:
  recipe-maintainers:
    - gino-m
    - jdbcode
    - jgarcia525
    - michaelfdewitt
    - naschmitz
    - schwehr
    - sgreenberg
    - sufyanAbbasi
    - kfriis33
