{% set name = "earthengine-api" %}
{% set version = "0.1.181" %}
{% set sha256 = "46cdf26f7628e902c6e8d2aa6e0eeb8bc5f52c5cad1265c3c1be4f9536c32d87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - earthengine = ee.cli.eecli:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - google-api-python-client
    - pyopenssl >=0.11
    - oauth2client

test:
  imports:
    - ee
    - ee.cli
  commands:
    - earthengine --help

about:
  home: https://earthengine.google.com/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Earth Engine Python API'
  description: |
    The Earth Engine Python API allows developers to interact with
    Google Earth Engine, a web platform for global scale geospatial analysis.
  doc_url: https://developers.google.com/earth-engine/
  dev_url: https://github.com/google/earthengine-api/

extra:
  recipe-maintainers:
    - arybak45
    - dag-ee
    - mike-d-d
    - saicheems
    - twotabbies
    - tylere
