{% set name = "earthengine-api" %}
{% set version = "0.1.284" %}
{% set sha256 = "71845c5bc440bdb2f5515a7a314f5a298d9b8bc28839df7394d2de2c60ed126b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - earthengine = ee.cli.eecli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - future
    - google-api-python-client >=1.12.1,<2
    - google-auth >=1.4.1
    - google-auth-httplib2 >=0.0.3
    - google-cloud-storage
    - httplib2 >=0.9.2,<1dev
    - python >=3.6
    - setuptools
    - six

test:
  imports:
    - ee
    - ee.cli
  commands:
    - earthengine --help

about:
  home: https://earthengine.google.com/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Earth Engine Python API
  description: |
    The Earth Engine Python API allows developers to interact with
    Google Earth Engine, a web platform for global scale geospatial analysis.
  doc_url: https://developers.google.com/earth-engine/
  dev_url: https://github.com/google/earthengine-api/

extra:
  recipe-maintainers:
    - arian487
    - bengalin
    - dag-ee
    - dotstarmoney
    - joannalcy
    - michaelfdewitt
    - mike-d-d
    - saicheems
    - sufyanAbbasi
    - twotabbies
    - tylere
