{% set name = "earthengine-api" %}
{% set version = "1.5.14" %}
{% set sha256 = "af45e0dbb6e190d77dc76aa77a7a3d7a74c82c0dec04e850befae19b378c13d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - earthengine = ee.cli.eecli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - google-api-python-client >=1.12.1
    - google-auth >=1.4.1
    - google-auth-httplib2 >=0.0.3
    - google-cloud-storage
    - httplib2 >=0.9.2,<1dev
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - ee
    - ee.cli
  commands:
    - earthengine --help

about:
  home: https://earthengine.google.com/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Earth Engine Python API
  description: |
    The Earth Engine Python API allows developers to interact with
    Google Earth Engine, a web platform for global scale geospatial analysis.
  doc_url: https://developers.google.com/earth-engine/
  dev_url: https://github.com/google/earthengine-api/

extra:
  recipe-maintainers:
    - naschmitz
    - bengalin
    - dag-ee
    - dotstarmoney
    - joannalcy
    - michaelfdewitt
    - mike-d-d
    - saicheems
    - schwehr
    - sufyanAbbasi
    - twotabbies
    - jgarcia525
